<table align="center" width="250" border="0" cellpadding="2" cellspacing="2">
    <tr>
    </tr>
    <tr class="even">
	<td class="subtitle ">
           <div align="center">
              <a href="../index.php" title="Useradmin Home">Back to Useradmin Home</a> 
    <!--           | <a href="logout.php" title="Logout of the Useradmin Database">Logout</a> -->
           </div>
        </td>
    </tr>
</table>
